grpc:
  server:
    name: "static"
    weight: 100
    addr: ":19093"
    etcdTTL: 60

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

mongodb:
  uri: "mongodb://root:root@localhost:27017"
  db: "kstack"